project_id = "acmlfzfliqupwxwoefdq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-shopify-order]
verify_jwt = false

[functions.fetch-shopify-products]
verify_jwt = false

[functions.get-all-collections]
verify_jwt = false

[functions.calculate-delivery-distance]
verify_jwt = false