project_id = "acmlfzfliqupwxwoefdq"

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.sync-customer-order]
verify_jwt = false