project_id = "acmlfzfliqupwxwoefdq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-shopify-order]
verify_jwt = false

[functions.fetch-shopify-products]
verify_jwt = false

[functions.get-all-collections]
verify_jwt = false

[functions.calculate-delivery-distance]
verify_jwt = false

[functions.send-ghl-sms]
verify_jwt = false

[functions.test-sms]
verify_jwt = false

[functions.check-delivery-alerts]
verify_jwt = false

[functions.create-affiliate]
verify_jwt = false

[functions.track-affiliate-referral]
verify_jwt = false

[functions.notify-commission-payout]
verify_jwt = false

[functions.sync-customer-order]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.track-abandoned-order]
verify_jwt = false

[functions.verify-admin-google]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.sync-custom-collection-to-shopify]
verify_jwt = false

[functions.validate-voucher]
verify_jwt = false

[functions.apply-voucher]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false